# Generated by Django 5.1.4 on 2025-01-15 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='estilista',
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
            preserve_default=False,
        ),
    ]
