# Generated by Django 5.1.4 on 2025-01-15 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_remove_cita_cliente_remove_cita_estilista_and_more'),
        ('cliente', '0005_initial'),
        ('estilista', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='estilista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estilista.estilista'),
            preserve_default=False,
        ),
    ]
