# Generated by Django 5.1.4 on 2025-01-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_remove_cliente_rol_cliente_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='roles',
        ),
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(default='cliente', max_length=30),
        ),
    ]
