# Generated by Django 5.1.4 on 2025-01-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_remove_cliente_roles_cliente_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_creacion'], 'permissions': (('puede_citar', 'Puede crear citas'),), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
