# Generated by Django 5.1.4 on 2025-01-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
