# Generated by Django 5.1.4 on 2025-01-14 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilista', '0002_estilista_deshabilitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estilista',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='estilista',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estilista',
            name='nombre',
        ),
        migrations.AddField(
            model_name='estilista',
            name='rol',
            field=models.CharField(default='estilista', max_length=20),
        ),
        migrations.AddField(
            model_name='estilista',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
