# Generated by Django 5.1.4 on 2025-01-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estilista', '0003_remove_estilista_apellido_remove_estilista_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estilista',
            name='deshabilitado',
        ),
    ]
