# Generated by Django 5.1.4 on 2025-01-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilista', '0007_remove_estilista_rol_estilista_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estilista',
            name='rol',
        ),
        migrations.AddField(
            model_name='estilista',
            name='rol',
            field=models.CharField(default='estilista', max_length=30),
        ),
    ]
