# Generated by Django 5.1.4 on 2025-01-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estilista', '0009_alter_estilista_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estilista',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'estilista', 'verbose_name_plural': 'estilistas'},
        ),
    ]
