# Generated by Django 5.1.4 on 2025-01-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_remove_cita_cliente_remove_cita_estilista_and_more'),
        ('estilista', '0004_remove_estilista_deshabilitado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estilista',
        ),
    ]
