# Generated by Django 5.1.4 on 2025-01-15 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estilista', '0005_delete_estilista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilista',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(default='estilista', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estilista',
                'verbose_name_plural': 'estilistas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
