# Generated by Django 5.1.4 on 2025-01-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilista', '0006_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estilista',
            name='rol',
        ),
        migrations.AddField(
            model_name='estilista',
            name='rol',
            field=models.ManyToManyField(to='usuarios.roles'),
        ),
    ]
