# Generated by Django 5.1.4 on 2025-01-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilista', '0010_alter_estilista_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilista',
            name='rol',
            field=models.CharField(default='estilistas', max_length=30),
        ),
    ]
