# Generated by Django 5.1.4 on 2025-01-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_remove_cita_cliente_remove_cita_estilista_and_more'),
        ('cliente', '0003_remove_cliente_apellido_remove_cliente_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
