# Generated by Django 5.1.4 on 2025-01-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_remove_cliente_rol_cliente_rol'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rol',
        ),
        migrations.AddField(
            model_name='cliente',
            name='roles',
            field=models.ManyToManyField(related_name='clientes', to='usuarios.roles'),
        ),
    ]
