# Generated by Django 5.1.4 on 2025-09-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(default='servicios/default.jpg', upload_to='servicios'),
        ),
    ]
