# Generated by Django 5.1.4 on 2025-01-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_remove_cliente_roles_cliente_rol'),
        ('estilista', '0008_remove_estilista_rol_estilista_rol'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
